### ISSUE TITLE
Investigate font test failures

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2008]
Running the test suite (`python -m pygame.tests`) locally on Windows yields this for me:

```
======================================================================
FAIL: test_match_font_all_exist (pygame.tests.font_test.FontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Local\Programs\Python\Python39\lib\site-packages\pygame\tests\font_test.py", line 121, in test_match_font_all_exist
    self.assertTrue(os.path.isabs(path) and os.path.isfile(path))
AssertionError: False is not true

======================================================================
FAIL: test_match_font_all_exist (pygame.tests.ftfont_test.FtFontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Local\Programs\Python\Python39\lib\site-packages\pygame\tests\font_test.py", line 121, in test_match_font_all_exist
    self.assertTrue(os.path.isabs(path) and os.path.isfile(path))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1828 tests in 39.370s

FAILED (failures=2)
```

Why is sysfont returning fonts that don't exist / aren't absolute paths?

**Comment by yunline** [comment]
Can't reperduce this on my computer.
```
PS X:\github\pygame-ce> & C:/Users/yunline/AppData/Local/Programs/Python/Python310/python.exe x:/github/pygame-ce/test/font_test.py
pygame-ce 2.2.0.dev1 (SDL 2.0.22, Python 3.10.6)
............................................................
----------------------------------------------------------------------
Ran 60 tests in 14.313s

OK
PS X:\github\pygame-ce> 
```

**Comment by yunline** [comment]
Oh I reperduced this after deleting the font `MS Mincho`.
```
pygame-ce 2.2.0.dev1 (SDL 2.0.22, Python 3.10.6)
.........F..................................................
======================================================================
FAIL: test_match_font_all_exist (__main__.FontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\github\pygame-ce\test\font_test.py", line 121, in test_match_font_all_exist
    self.assertTrue(os.path.isabs(path) and os.path.isfile(path))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 60 tests in 5.991s

FAILED (failures=1)
```

**Comment by yunline** [comment]
> Oh I reperduced this after deleting the font `MS Mincho`.

![image](https://user-images.githubusercontent.com/31395137/224481073-bffa8d00-3584-4e47-a19a-5dc292f7912e.png)

These failures may happens when some of fonts were deleted but not removed from the registry.

**Comment by yunline** [comment]
> Oh I reperduced this after deleting the font `MS Mincho`.

![image](https://user-images.githubusercontent.com/31395137/224481073-bffa8d00-3584-4e47-a19a-5dc292f7912e.png)

These failures may happens when some of fonts were deleted but not removed from the registry.

**Comment by ankith26** [comment]
This has been fixed by the linked PR but this issue wasn't closed, so closing now
