### ISSUE TITLE
Unable to load `.mod` audio file.

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2158]
**TestCode:** https://mcpalmer1980.itch.io/flyboy
The game runs correctly when using pygame2.4.0, SDL2.26.4, SDL-mixer2.6.2.
However, It returns an error when using pygame-ce 2.2.1, SDL2.26.4,  SDL-mixer2.6.3.
```
Traceback (most recent call last):
  File "x:\python\Flyboy\run_game.py", line 16, in <module>
    exec('import {} as main'.format(file))
  File "<string>", line 1, in <module>
  File "x:\python\Flyboy\lib\main.py", line 1558, in <module>
    start = game()
  File "x:\python\Flyboy\lib\main.py", line 45, in __init__
    self.clips('intro', skip_delay)
  File "x:\python\Flyboy\lib\effects.py", line 1089, in __call__
    sequence()
  File "x:\python\Flyboy\lib\effects.py", line 1109, in Intro
    pygame.mixer_music.load(sound_dir+'intro.mod')
pygame.error: Unrecognized audio format
```

**Comment by Starbuck5** [comment]
This is fixed in https://github.com/pygame-community/pygame-ce/pull/2152

**Comment by yunline** [comment]
> This is fixed in #2152

This bug still exists

**Comment by Starbuck5** [comment]
You built with the new commit, but did you regenerate your dependencies? Are you still using SDL_mixer 2.6.3?

**Comment by yunline** [comment]
> You built with the new commit, but did you regenerate your dependencies? Are you still using SDL_mixer 2.6.3?

Oh it works, my bad.
