### ISSUE TITLE
Method to normalize zero vectors

### ISSUE THREAD

**Issue by tigeryzhang** [pygame-community/pygame-ce#2269]
**Description**
When normalizing a vector, it is necessary to first check it is not of length zero, otherwise the program will crash.

The game engine bevy has a method for its `Vec`s that is `normalize_or_zero()` that allows you to normalize a vector that is potentially of length zero, where it returns a zero vector if that is the case, otherwise normalizing it.

I think this would be useful to have in pygame, as it saves having to type an extra line pretty much every time you want to normalize a vector.

**Comment by bilhox** [comment]
Mathematically speaking, it's impossible to normalize a zero vector, so returning a zero vector would be weird. That's why, I don't agree with you.

**Comment by Yu266426** [comment]
Well, I don't agree in the sense that just because something doesn't "make sense mathematically" means that a more convenient method shouldn't exist.

But also, that's why the method is called `normalize_OR_ZERO`, which I think helps illustrate that it isn't just normalizing it.

**Comment by bigwhoopgames** [comment]
I would be in support of having this method added. In nearly ever instance of me using normalize() I use a zero vector if I can't normalize.

**Comment by Matiiss** [comment]
I like the idea of having a way to conveniently get the zero vector back when normalizing, the proposed method's name is quite clear in what it would do and thus I don't see how it wouldn't make sense mathematically either, you either can normalize or you return a zero vector.

An alternative idea would be to add an optional argument to `normalize`, like `zero` that would achieve the same thing: `vec.normalize(zero=True)` (perhaps, it could be a positional-only argument for performance: `vec.normalize(True)` albeit that makes it less readable, but maybe using keyword args doesn't make it all that slow, so that should be tested)

**Comment by DaNubCoding** [comment]
Perhaps `xnormalize` is also an option, meaning "exclusive normalize", where it will normalize everything excluding zero vector in which case it is handled differently. This is easier to type and doesn't clutter code with long method names. Stuff like FRect uses a similar method of naming.

**Comment by Mega-JC** [comment]
I'm not sure if pygame needs this to be honest, especially if there is already a super simple solution to this problem of getting a potential `ValueError`: Simply checking it using an if statement, or short-circuting with `and` by writing the expression `vector and vector.normalize()`. In the latter case, if `vector` is a zero vector, the expression will simply  return `vector`. If `vector` is not a zero vector, `vector.normalize()` will be returned instead. This seems to be the exact behavior desired here. 

Another example:
```py
>>> from pygame import Vector2
>>> 
>>> vec_a = Vector2(5, 0)
>>> vec_a.normalize()
Vector2(1, 0)
>>> 
>>> vec_b = Vector2(0, 0)
>>> vec_b.normalize()
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    vec_b.normalize()
ValueError: Can't normalize Vector of length Zero
>>>
>>> vec_a_norm_or_zero = vec_a and vec_a.normalize()
>>> vec_a_norm_or_zero
Vector2(1, 0)
>>>
>>> vec_b_norm_or_zero = vec_b and vec_b.normalize()
>>> vec_b_norm_or_zero
Vector2(0, 0)
```

**Comment by bilhox** [comment]
I think however we should have prebuilt Vectors (Like in Unity I think), like Vector2.zero ``(0 , 0)`` for example. So it would more easy to compare and check if a vector in null. (or a method that returns true if it's zero ?)

**Comment by itzpr3d4t0r** [comment]
> I think however we should have prebuilt Vectors (Like in Unity I think), like Vector2.zero (0 , 0) for example. So it would more easy to compare and check if a vector in null. (or a method that returns true if it's zero ?)

There's no need for such method, you can already do `if not vector:`, vectors support bool checks.

**Comment by Matiiss** [comment]
> I think however we should have prebuilt Vectors (Like in Unity I think), like Vector2.zero `(0 , 0)` for example. So it would more easy to compare and check if a vector in null. (or a method that returns true if it's zero ?)

Aside from vectors supporting boolean checks, you can get a zero vector by simply instantiating a vector: `pygame.Vector2()`

**Comment by DaNubCoding** [comment]
> Simply checking the vector's thuthiness using an `if` statement, or short-circuiting with `and` by writing the expression `vector and vector.normalize()`. 

These methods work, however they are either cumbersome to write when `normalize` is used frequently (`if` statement solution) or simply unclear to the reader as to what they are doing (`and` solution).

**Comment by Mega-JC** [comment]
> or simply unclear to the reader as to what they are doing (`and` solution).

To clarify, `vector and vector.normalize()` (short-circuting with `and`) is the same as `vector.normalize() if vector else vector` (ternary expression), for those who prefer the longer, more explicit syntax. The former just seemed to be the shortest and the easiest to substitute a bare `.normalize()` method call with in a long sequence of vector operations (you implied wanting a concise solution).

**Comment by DaNubCoding** [comment]
> To clarify, `vector and vector.normalize()` (short-circuting with `and`) is the same as `vector.normalize() if vector else vector` (ternary expression), for those who prefer the longer, more explicit syntax. The former just seemed to be the shortest and the easiest to substitute a bare `.normalize()` method call with in a long sequence of vector operations (Yu266426 implied wanting a concise solution).

Yes the short-circuiting solution is a good solution as of now, but I think it can be made clearer with the implementation of a `normalize_or_zero()`. It is indeed a more concise version of the ternary solution, but it loses some clarity in comparison.

**Comment by JiffyRob** [comment]
Just want to point out, if we did implement this, would we also want to do something similar with `scale_to_length()`?  If we don't it's a simple `normalize(zero=True) * length` but the whole point of this issue is conciseness.  I would be in favor of the normalize method just because I use it so often and end up erring out and having to write boilerplate for it constantly.  You're right to say that it's pretty simple just to short circuit, but when it is needed so dang often the trade-off makes less sense.  Also many pygame users are just learning python and don't know how short circuiting works.  At the very least I would put a note in the docs.

**Comment by bilhox** [comment]
At the beginning, I was against this idea because it's scientifically wrong. So I checked how it was done on other game engine like Unity and godot, and I found that they both return a zero vector, which joins the idea of the original message.

So if anyone is looking at this issue and wants to implement this feature, this is the way to go imo.

**Comment by Doublestuf** [comment]
I'd love to take this issue :). It'd be my first contribution to pygame-ce (been wanting to contribute to it for a while) and second contribution overall. Might take a while, though.

**Comment by bilhox** [comment]
Hi @Doublestuf ,

Sure you can do it ! The code you need to modify should be in ``src_c/math.c`` in ``vector_normalize_ip``. You'll also have to write a new test in ``test/math_test.py``, and update the documentation in ``docs/reST/ref/math.rst`` in the method paragraph.

**Comment by oddbookworm** [comment]
I'm still not convinced that this is necessary. It may be what bona-fide game engines do, but pygame-ce is not a game engine. There are ways I can think of that being able to "normalize" the zero vector could go pretty wrong because you're expecting the result to be nonzero in your calculations. IMO implementing this just moves the problem from normalizing to wherever else you use the resulting normalized vector. You still need to be cognizant of the case you have the zero vector, so I don't see any benefit to this in general

**Comment by aatle** [comment]
Note that the behavior of `.normalize_ip()` is currently equivalent to `.scale_to_length(1)`, so the latter might also need changes.

**Comment by Yu266426** [comment]
I still think a separate method is the way to go here. That way the original functionality is unchanged, while providing a more convenient option for situations like normalising input, or maybe getting an offset direction for AI might end up in the player.

**Comment by Mega-JC** [comment]
I'm now neutral on this idea. There's a suggested workaround, but it wouldn't hurt to have this imo, if the scope of changes required is minimal.

**Comment by oddbookworm** [comment]
I'm still very against this idea. I just see too many problems getting moved into whatever other complicated code you have because you expect the result of a normalize call to be, well, normalized. And there's no world in which I imagine calling normalize on a vector, then checking if it's normalized should return anything but True. And I certainly won't approve of any attempts to make an exception for the zero vector being normalized. It's just way too easy at that point to create obscure bugs that would be a pain to debug. If you still have to be cognizant of the zero vector, even with normalizing allowing it, then I see no point in allowing it.

And changing the current behavior is out of the question. That would break backwards compatibility. It would have to be either a new argument or a whole new function.

**Comment by Matiiss** [comment]
> And changing the current behavior is out of the question.

I don't think it's entirely out of question, especially when moving to a new major version (such as `pygame-ce v3.0`). However, I agree that we probably shouldn't.

I think currently the best move forward (and I think we should move forward, it seems like a pretty useful convenience method) is one of the following:
- `vec.normalize(zero=True)`
- `vec.xnormalize()` or `vec.znormalize()` or some similar variation
- `vec.normalize_or_zero()`

**Comment by oddbookworm** [comment]
Again, it doesn't actually solve a problem except in the most basic of user code. Generally, the user is still going to have to filter out the zero vector anyway.

**Comment by Starbuck5** [comment]
So a few months ago I was watching clear code's pygame tutorial, at this timestamp https://youtu.be/8OMghdHP-zs?si=dvq7ndecJIGEy3rg&t=6521, and he had to explain to the audience to write a conditional check because otherwise normalize will raise an exception. And it reminded me of this issue, I was like why should it do that.

I've added this to the 3.0 milestone for consideration as a behavior change for that release.

I did a little bit of digging on other references for vector normalization behavior. I believe this analysis shows a clear precedent towards zero vector normalization.

Zero vector -> zero vector
--------------------

Unity: zero vector returns zero vector
https://docs.unity3d.com/6000.4/Documentation/ScriptReference/Vector2-normalized.html
Raylib: zero vector returns zero vector
https://github.com/raysan5/raylib/blob/aaacda6e147031f2af0cfb6c1fd7e64d761ddb1f/src/raymath.h#L430-L443
Godot: zero vector returns zero vector
https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-normalized
Unreal: zero vector returns zero vector (I think this is the right spot to look?)
https://dev.epicgames.com/documentation/unreal-engine/BlueprintAPI/Math/Vector/Normalize?application_version=5.8&lang=en-US
Phaser: zero vector returns zero vector
https://github.com/phaserjs/phaser/blob/7304c64effaa4a1be5b8bf02ab13143a76108a19/src/math/Vector2.js#L495-L520

Additional function provided for this use case
--------------------

Bevy: zero vector produces "invalid results", also offers normalize_or_zero method.
https://docs.rs/bevy/latest/bevy/math/struct.Vec2.html#method.normalize
Wasabigeom (LordMauve's project): zero division error, offers safe_normalize function as well
https://wasabigeom.readthedocs.io/en/stable/api.html#wasabigeom.vec2.normalized, https://github.com/lordmauve/wasabi-geom/blob/a3a2848e31baadaca644e19a5712a6f0569ec3b5/wasabigeom.pyx#L309-L314

Zero vector -> corrupted data / bad?
--------------------

Monogame: returns vector with NaN (they don't endorse)
https://github.com/MonoGame/MonoGame/issues/8125
GLM: crashes
https://github.com/g-truc/glm/blob/master/manual.md#-710-why-some-glm-functions-can-crash-because-of-division-by-zero
HLSL: "indefinite"
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-normalize

**Comment by oddbookworm** [comment]
I still don't agree that we should support it. We cannot compare ourselves against full engines like Unity, Unreal, or Godot. Those engines are purpose-built to minimize the amount of user error that can cause issues, like not checking inputs religiously. I cannot say I can think of a good use-case for allowing normalizing of the zero vector that makes sense for us to allow. In fact, I would say that it's still a good idea to check for zero, because in most cases you do nothing. In which case, you can bypass a whole buncha math and save yourself cpu cycles

**Comment by oddbookworm** [comment]
Wasabigeom's safe_normalize also returns what's apparently an arbitrary/random unit vector when the zero vector is passed in, and that makes absolutely no sense to do either

**Comment by Starbuck5** [comment]
In the Clear Code video I linked in my comment, a Vector2 is used to determine an entity's direction. Input by direction is added to the vector, and to prevent faster movement on diagonals than when traveling straight, the vector is normalized. The desired behavior for a zero vector is a zero vector.

I wanted to look at examples in real pygame-ce code, and I happened to have several games from the pygame community winter jam downloaded. (Link: https://itch.io/jam/pygame-community-winter-jam-2026)

In Frostbound, normalize is used in a few places for this same direction use case. The snowman direction and slime jump direction seem to just use whatever the last direction was if the direction length is zero, which is safe but maybe not the most correct? For the indicator class, it has a special skip on zero vector that leads to it not rendering the indicator at all, which again works but maybe is not the most correct behavior.  The gun class does not have the extra handling around normalize() to make it safe, so it is possible to crash the game if you mouse directly over the player. In all of these locations, a zero normalize would've produced correct results.

```
  File "C:\Users\charl\Downloads\winterjam\Frostbound\scripts\entities.py", line 97, in update
    self.direction = (self.mpos - pygame.Vector2(self.player.rect.centerx, self.player.rect.centery)).normalize()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Can't normalize Vector of length zero
``` 

Ultra Cold also uses normalize, with several guarded / one unguarded location.
` if (g.player.dp.x != 0 and g.player.dp.y != 0) and g.player.dp.normalize() == touched_entity.look_dir:`
`proj_dir =  player_diff.normalize() if player_diff.magnitude_squared() > 0.0 else self.look_dir`

The unguarded location is in the Projectile class constructor.
```py
# Presume this won't change after spawn
self.dir:p.Vector2 = p.Vector2(dir).normalize()
self.look_dir = self.dir
self.vel = self.dir * self.move_speed * g.TW
```
This will be a latent crash if a zero direction is ever passed into it, which I was not able to find a way to do. Being tile based helps avoid these crashes. I confirmed that a zero vector result here would be fine by manually setting it to a zero vector and observing the projectiles just stayed still.

-------------------------------------------
With these examples in mind, I maintain my hypothesis that normalize() crashing is an unnecessary footgun for this library. In the two jam games I had downloaded that used the normalize() function, the developers employed a multitude of different strategies to get around it, likely encountering crashes live in development or testing, wasting valuable time, when the systems would have operated perfectly fine if the normalize function returned a zero vector when given a zero vector. And despite the developer clearly being aware of this issue with normalize, it is still possible to crash Frostbound with it.

**Comment by oddbookworm** [comment]
I'm retracting all of my complaints about this, and @Starbuck5 and I talked it out and it seems like the way forward for this issue lies in 3.x. In 3.x, `normalize` will accept the zero vector by default. That being said, I don't expect any changes in 2.x. Adding a new method is out of the question if it's going to be almost immediately useless in 3.x, and adding an argument only to 2.x seems like it'll just end up being a recipe for confusion.
