### ISSUE TITLE
`pg_IntFromObj`

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2404]
```
>>> import pygame 
pygame-ce 2.4.0.dev1 (SDL 2.26.5, Python 3.10.6)
>>> sf = pygame.Surface((100,100)) 
>>> pygame.draw.circle(sf, "red", (0,0), 1<<33) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: radius argument must be a number
>>>
```

**Comment by yunline** [comment]
Actually, no matter what type of exception is raised inside, it always returns `TypeError`.
```py
import pygame

class Foo:
    def __index__(self):
        #return 114514
        raise NameError("Foo is not a good name.")
    
sf = pygame.Surface((100,100))

# Expected behavior: raises a NameError
pygame.draw.circle(sf, "red", (0,0), Foo())
```
```py
Traceback (most recent call last):
  File "x:\python\pygame_test\pgint.py", line 11, in <module>
    pygame.draw.circle(sf, "red", (0,0), Foo())
TypeError: radius argument must be a number
```

**Comment by yunline** [comment]
When the input is a float, the function doesn't raise any error even if the value is way higher than `INT_MAX`.

```py
import pygame
sf = pygame.Surface((100,100))

pygame.draw.circle(sf, "red", (0,0), 1e40)
```

```
# No Error Raised
```

**Comment by yunline** [comment]
I'm trying to fix this.
