### ISSUE TITLE
Seg fault caused when attempting vec4 += vec3 in a fragment shader

### ISSUE THREAD

**Issue by d-orm** [pygame-community/pygame-ce#2686]
It's obviously a GLSL/OpenGL error, but causes a pygame seg fault so thought you guys might be interested.

**Environment:**

- **Operating system**: Windows 10
- **Python version** : 3.12.0
- **SDL version**: 2.28.5
- **pygame-ce version**: 2.4.0
- **Relevant hardware**: N/A

**Current behavior:**

Segmentation Fault when attempting to += a vec4 by a vec3 (obviously not something that's valid in GLSL, but it's an easy mistake to make)

**Expected behavior:**

A more graceful exception raised, with a message/log provided by the OpenGL context library.

**Screenshots**

N/A

**Steps to reproduce:**

Uncomment line 43 in fragment shader code in the MRE below.

**Test code**

```
import pygame
import zengl
import sys


SCREEN_SIZE = (1600, 900)

pygame.display.set_mode(SCREEN_SIZE, flags=pygame.OPENGL | pygame.DOUBLEBUF)

ctx = zengl.context()

output = ctx.image(SCREEN_SIZE, 'rgba8unorm', samples=4)

pipeline = ctx.pipeline(
    vertex_shader="""
        #version 300 es
        precision highp float;

        vec2 vertex[4] = vec2[](
            vec2(-1.0, -1.0),
            vec2(-1.0, 1.0),
            vec2(1.0, -1.0),
            vec2(1.0, 1.0)
        );

        out vec2 uv;

        void main() {
            uv = vertex[gl_VertexID] * vec2(0.5, -0.5) + 0.5;
            gl_Position = vec4(vertex[gl_VertexID], 0.0, 1.0);
        }
    """,
    fragment_shader="""
        #version 300 es
        precision highp float;

        in vec2 uv;
        out vec4 fragColor;

        void main() {
            vec4 color = vec4(uv, 1.0, 1.0);
            vec3 letsSegFaultIt = vec3(1.0, 0.0, 0.0);
            // color += letsSegFaultIt; // Uncomment this line to segfault
            fragColor = color;
        }
    """,
    framebuffer=[output],
    vertex_count=4,
    topology='triangle_strip',
)

clock = pygame.time.Clock()


def main():
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
        ctx.new_frame()
        pipeline.render()
        output.blit()
        ctx.end_frame()
        pygame.display.flip()
        clock.tick(60)


if __name__ == "__main__":
    main()

```

**Stack trace/error output/other error logs**

```
pygame-ce 2.4.0 (SDL 2.28.5, Python 3.12.0)
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00005bb4 (most recent call first):
  File "c:\...\main.py", line 14 in <module>

Extension modules: _wmi, pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.window, pygame.display, pygame.draw, pygame.joystick, pygame.event, pygame.imageext, pygame.image, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame.system, zengl, pygame._freetype (total: 42)
```

**Comment by Matiiss** [comment]
The segfault is caused by `zengl` (in some capacity or other), I managed to reduce your example to this:
```py
import zengl

zengl.init(zengl.loader(headless=True))
ctx = zengl.context()

output = ctx.image((1600, 900), 'rgba8unorm', samples=4)

pipeline = ctx.pipeline(
    vertex_shader="""
        #version 300 es
        void main() {}
    """,
    fragment_shader="""
        #version 300 es

        void main() {
            vec4 color = vec4(0.0, 0.0, 1.0, 1.0);
            vec3 letsSegFaultIt = vec3(1.0, 0.0, 0.0);
            color += letsSegFaultIt;
        }
    """,
    framebuffer=[output],
    vertex_count=4,
    topology='triangle_strip',
)
```
For me (on Windows) it exits with exit code `0xC0000005`, which is basically a segfault. Because you `import pygame` it catches this segfault and emits the usual segfault report.

**Comment by d-orm** [comment]
Interesting, for me your above example just exits without any error code, but obviously doesn't compile still.

Usually the zengl (or moderngl) internal shader errors catcher picks up things like this, say if you pass 4 floats to a vec3 constructor you get:

```
Traceback (most recent call last):
  File "c:\...\main.py", line 8, in <module>
    pipeline = ctx.pipeline(
               ^^^^^^^^^^^^^
  File "C:\...\Lib\site-packages\_zengl.py", line 549, in compile_error
    raise ValueError(f"{name} Error\n\n{log}")
ValueError: Fragment Shader Error

ERROR: 0:10: 'constructor' : too many arguments
```

But it seems that the vec4 += vec3 error doesn't get picked up by `zengl` in this way which is why it causes Pygame to seg fault I assume. I guess this issue can be closed if it's not related directly to Pygame and the seg fault is expected, and I'll report it to zengl in case it's of interest.

Thanks
