### ISSUE TITLE
Adding the __getattr__ method to DirtySprite may lead to infinite recursion

### ISSUE THREAD

**Issue by LondonClass** [pygame-community/pygame-ce#2790]
Many ways can lead to infinite recursion.

1.Just print self.
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        super().__init__()
    
    def __getattr__(self, name):
        print(self)

sprite = MySprite()
```

2.Using an undefined variable
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        super().__init__()
        self.a = 0
    
    def __getattr__(self, name):
        print(self.a)

sprite = MySprite()
```

If I want to implement this function:
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        super().__init__()
        self.image = pygame.Surface((100, 100))
    
    def __getattr__(self, name):
        return getattr(self.image, name)

sprite = MySprite()
```
Method 1:
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        self.intialized = False
        super().__init__()
        self.intialized = True
        self.image = pygame.Surface((100, 100))
    
    def __getattr__(self, name):
        if self.intialized:
            return getattr(self.image, name)

sprite = MySprite()
```
Method 2:
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        super().__init__()
        self.image = pygame.Surface((100, 100))
    
    def __getattr__(self, name):
        if name == "_Sprite__image":
            return
        return getattr(self.image, name)

sprite = MySprite()
```
Method 3:
```python
import pygame

class MySprite(pygame.sprite.DirtySprite):
    def __init__(self, *args):
        self.image = None
        super().__init__()
        self.image = pygame.Surface((100, 100))
    
    def __getattr__(self, name):
        return getattr(self.image, name)

sprite = MySprite()
```

**Comment by Starbuck5** [comment]
I don't think this has anything to do with the sprite class, it's just your use of `__getattr__`.

```py
class Test:
    def __init__(self, val):
        self.val = val

    def __getattr__(self, name):
        return self.x
    

a = Test(2)
print(a.x)
```

```
Traceback (most recent call last):
  File "C:\Users\charl\Desktop\test7.py", line 10, in <module>
    print(a.x)
  File "C:\Users\charl\Desktop\test7.py", line 6, in __getattr__
    return self.x
  File "C:\Users\charl\Desktop\test7.py", line 6, in __getattr__
    return self.x
  File "C:\Users\charl\Desktop\test7.py", line 6, in __getattr__
    return self.x
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```
