### ISSUE TITLE
Local test fails: When compiling from Source on Raspberry Pi

### ISSUE THREAD

**Issue by MyreMylar** [pygame-community/pygame-ce#2876]
Not too many:

```
======================================================================
FAIL: test_iconify (pygame.tests.display_test.DisplayModuleTest.test_iconify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/display_test.py", line 431, in test_iconify
    self.assertTrue(window_minimized_event)
AssertionError: False is not true

======================================================================
ERROR: test_get__owned_empty_type (pygame.tests.scrap_test.ScrapModuleTest.test_get__owned_empty_type)
Ensures get works when there is no data of the requested type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/scrap_test.py", line 65, in test_get__owned_empty_type
    scrap.put(pygame.SCRAP_TEXT, b"text to clipboard")
pygame.error: content could not be placed in clipboard.

======================================================================
ERROR: test_init__reinit (pygame.tests.scrap_test.ScrapModuleTest.test_init__reinit)
Ensures reinitializing the scrap module doesn't clear its data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/scrap_test.py", line 37, in test_init__reinit
    scrap.put(data_type, expected_data)
pygame.error: content could not be placed in clipboard.

======================================================================
ERROR: test_put (pygame.tests.scrap_test.ScrapModuleTest.test_put)
Ensures put can place data into the clipboard
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/scrap_test.py", line 114, in test_put
    scrap.put(DATA_TYPE, b"buf")
pygame.error: content could not be placed in clipboard.

======================================================================
ERROR: test_put__bmp_image (pygame.tests.scrap_test.ScrapModuleTest.test_put__bmp_image)
Ensures put can place a BMP image into the clipboard.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/scrap_test.py", line 104, in test_put__bmp_image
    scrap.put(pygame.SCRAP_BMP, expected_bytes)
pygame.error: content could not be placed in clipboard.

======================================================================
ERROR: test_put__text (pygame.tests.scrap_test.ScrapModuleTest.test_put__text)
Ensures put can place text into the clipboard.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Dan/Programming/pygame-ce/virtual_env/lib/python3.11/site-packages/pygame/tests/scrap_test.py", line 91, in test_put__text
    scrap.put(pygame.SCRAP_TEXT, b"Hello world")
pygame.error: content could not be placed in clipboard.

----------------------------------------------------------------------
Ran 2198 tests in 363.807s

FAILED (failures=1, errors=5)

```

These also popped up:

```
loading pygame.tests.mixer_music_test
[src/libmpg123/id3.c:INT123_parse_new_id3():1086] error: Whoa! ID3v2 frame claims to be larger than the whole rest of the tag.
[src/libmpg123/id3.c:INT123_parse_new_id3():1086] error: Whoa! ID3v2 frame claims to be larger than the whole rest of the tag.

```

Test still passes - but that seems to indicate something is wonky in the mixer test data (maybe intentionally).

PyCharm runs pretty slow on the Pi so it is not the best debugging environment, but at least it gets all the way through the tests at the minute!

**Comment by ankith26** [comment]
Apart from the `test_iconify` fail, I get the every other fail locally, and I've always been ignoring it considering that the scrap module is in it's current semi-broken state

**Comment by ankith26** [comment]
The 5 scrap test fails should be gone now that #3473 is merged in. As for the iconify test, I think it's an intermittent fail. I'm closing this issue for now but if the issue is persisting feel free to reopen.
